---
language: ru
api:
  frontend: https://example.com/frontend
  asterisk: http://127.0.0.1/asterisk
  internal: http://127.0.0.1/internal
  mobile: https://example.com/mobile
mobile:
  web_server_base_path: https://example.com/static/
  payments: true
  payments_url: https://example.com/static/payments/template.html
  city_cams: false
  support_phone: "+7(4752)429999"
  chat: true
  chat_url: "<!-- your chat url or remove it and use talkMe by default with options
    below--!>"
  talk_me_id: "<!-- put your talkMe chat id here --!>"
  talk_me_domain: "<!-- put your talkMe chat domain id here --!>"
  talk_me_token: "<!-- put your talkMe chat rest Api Token here --!>"
  phonePattern: '7 (###) ###-##-##'
  tt_project: TDM
  tt_workflow: mobile
  tt_user: mobile
  time_zone: Europe/Moscow
  guest_access: turnOnOnly
  cctv_view: map
  _comments_active_tab: 'Active app''s tab at start. One of: addresses, notifications,
    chat, pay, menu. The default value is addresses'
  active_tab: addresses
db:
  dsn: pgsql:host=127.0.0.1;port=5433;dbname=rbt
  username: rbt
  password: rbt
redis:
  host: 127.0.0.1
  port: 6379
  frontend_cache_ttl: 600
  backends_cache_ttl: 604800
  max_allowed_tokens: 15
  token_idle_ttl: 3600
clickhouse:
  host: localhost
  port: '8123'
  username: default
  password: qqq
  database: default
backends:
  authentication:
    backend: internal
  authorization:
    backend: allow
  accounting:
    backend: syslog
  users:
    backend: internal
  geocoder:
    backend: dadata
    token: "<!-- your dadata token here --!>"
  files:
    backend: mongo
  addresses:
    backend: internal
  households:
    backend: internal
  cameras:
    backend: internal
  isdn:
    backend: lanta
    common_secret: "<!-- your secret here --!>"
    confirm_method: outgoingCall
  inbox:
    backend: clickhouse
  plog:
    backend: clickhouse
    _comment_time_shift: "<!-- your time shift in seconds from current time as the
      end timepoint for processing plog_* tables (hint 60) --!>"
    time_shift: 60
    _comment_max_call_length: "<!-- your max call length in seconds for backward processing
      call events (hint 120) --!>"
    max_call_length: 120
    _comment_ttl_temp_record: "<!-- your time to live in seconds for temporary data
      in plog_* tables (hint 86400 - one day) --!>"
    ttl_temp_record: 86400
    _comment_ttl_camshot_days: "<!-- your time to live in days for camshots (hint
      180 - approx. half year) --!>"
    ttl_camshot_days: 180
    _comment_back_time_shift_video_shot: "<!-- your back time shift in seconds for
      receiving video shot from media server (hint 3) --!>"
    back_time_shift_video_shot: 3
    cron_process_events_scheduler: minutely
  configs:
    backend: json
  dvr:
    backend: internal
    servers:
    - title: Local server
      type: nimble or flussonic or  or trassir
      url: https://video.server.hostname:8443
      token: "<!-- mediaserver security token here (only if you use it) --!>"
      hlsMode: mpegts
      management_ip: 127.0.0.1
      management_port: '8086'
      management_token: "<!-- management token --!>"
  dvr_exports:
    backend: mongo
    dvr_files_ttl: 259200
  sip:
    backend: internal
    servers:
    - title: First server
      type: asterisk
      trunk: first
      ip: "<!-- your asterisk server external ip here --!>"
      sip_tcp_port: 5060
      sip_udp_port: 5060
    stuns:
    - stun:stun.l.google.com:19302
  frs:
    backend: internal
    open_door_timeout: 10
    cron_sync_data_scheduler: 5min
    servers:
    - title: First server
      url: http://127.0.0.1:9051
  cs:
    backend: internal
  mqtt:
    backend: internal
    agent: http://127.0.0.1:8082/broadcast
    ws: wss://example.com/mqtt
    mqtt: mqtt://127.0.0.1:1883
    username: rbt
    password: "<!-- your mosquitto password here --!>"
  issue_adapter:
    backend: lanta
    tt_url: "<!-- your tt url here --!>"
    tt_token: "<!-- your tt bearer token here --!>"
    anti_spam_interval: "<!-- your minimum interval in seconds which permits creating
      similar issue (hint 86400 - one day) --!>"
  queue:
    backend: internal
email:
  server: 127.0.0.1
  port: 587
  username: "<!-- your smtp login here -->"
  password: "<!-- your smtp password here -->"
  from: RBT
telegram:
  bot: "<!-- your telegram bot token here --!>"
document_builder:
  bin: "/opt/onlyoffice/documentbuilder/docbuilder"
  tmp: "/tmp"
syslog_servers:
  beward:
  - syslog.udp:127.0.0.1:45450
  beward_ds:
  - syslog.udp:127.0.0.1:45451
  qtech:
  - syslog.udp:127.0.0.1:45452
  is:
  - syslog.udp:127.0.0.1:45453
  hikvision:
  - syslog.udp:127.0.0.1:45454
  akuvox:
  - syslog.udp:127.0.0.1:45455
  rubetek:
  - syslog.udp:127.0.0.1:45456
  sputnik:
  - https://your-http(s)-server:45457/events/sputnik
ntp_servers:
- ntp:<-- your ntp server ip here -->:123
